name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Instalar dependencias
      run: npm ci

    - name: Compilar TypeScript
      run: npm run build

    - name: Ejecutar pruebas
      run: npm test

    - name: Mostrar cobertura
      run: cat coverage/lcov.info || echo "No hay reporte de cobertura"
